### ISSUE TITLE
`then_enter_with(None)` makes the stub return `None` instead of an enterable context manager

### ISSUE THREAD

**Issue by SyntaxColoring** [mcous/decoy#135]
If you have production code that looks like this:

```python
with foo.bar(bar_arg) as baz:
    ...
```

Then its Decoy test might do:

```python
bar_arg_captor = matchers.Captor()
decoy.when(foo.bar(bar_arg_captor())).then_enter_with("baz value")
```

But sometimes the `with` statement has no `as` clause:

```python
with foo.bar(bar_arg):
    ...
```

I expected this to work:

```python
bar_arg_captor = matchers.Captor()
decoy.when(foo.bar(bar_arg_captor())).then_enter_with(None)
```

But this causes the production code's call to `foo.bar(bar_arg)` to return `None`. It should instead return *a context manager that returns `None` when it's entered.*

It looks to me like this is an unintentional side-effect of the way `StubBehavior` works internally:

https://github.com/mcous/decoy/blob/c23d145a0cbd16672515a3232be67bb9f9f722b6/decoy/stub_store.py#L7-L14

It can't distinguish between being configured with a `context_value` that's `None` versus not being configured with a `context_value` at all.

To solve a similar problem, the implementation of `dataclasses` uses [a special `MISSING` sentinel value that's distinct from `None`](https://docs.python.org/3/library/dataclasses.html#dataclasses.MISSING:~:text=As%20shown%20above%2C%20the%20MISSING%20value%20is%20a%20sentinel%20object%20used%20to%20detect%20if%20some%20parameters%20are%20provided%20by%20the%20user.%20This%20sentinel%20is%20used%20because%20None%20is%20a%20valid%20value%20for%20some%20parameters%20with%20a%20distinct%20meaning.%20No%20code%20should%20directly%20use%20the%20MISSING%20value.). Maybe a similar pattern could work here.

**Comment by SyntaxColoring** [comment]
An easy workaround is to provide some arbitrary dummy value to `then_enter_with`, like `then_enter_with("<value unused>").

**Comment by mcous** [comment]
Shoot, we need a sentinel for this to work.

Stubbing a `None` context value is interesting, though, because it seems to me like it would be difficult to construct a test that ensures a stubbed context manager is actually used. Since there's no value to interact with, a stubbed `None` can't validate proper usage.

I think the better workaround here is to return a CM mock with its `__enter__` etc. stubbed out, as in: https://mike.cousins.io/decoy/advanced/context-managers/#general-context-managers
